// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone', 'marionette', 'cs!session', 'cs!collections/media-types', 'cs!models/content/book', 'cs!models/content/folder', 'cs!models/content/module', 'less!styles/main.less'], function(Backbone, Marionette, session, mediaTypes, Book, Folder, Module) {
    var app;
    app = new Marionette.Application();
    app.root = '';
    app.addRegions({
      main: '#main'
    });
    app.on('start', function(options) {
      var _this = this;
      mediaTypes.add(Book);
      mediaTypes.add(Folder);
      mediaTypes.add(Module);
      require(['cs!controllers/routing', 'cs!router'], function(controller) {
        controller.main = _this.main;
        if (!Backbone.History.started) {
          return Backbone.history.start({
            root: app.root
          });
        }
      });
      return session.login();
    });
    return app;
  });

}).call(this);
